# Pre-commit hooks for Consensys AI code review
# See https://pre-commit.com for more information

- id: consensys-review
  name: Consensys AI Code Review
  description: Multi-agent AI code review with debate and voting
  entry: consensys review --quick
  language: python
  types: [python]
  pass_filenames: true
  require_serial: false
  verbose: true
  stages: [commit]

- id: consensys-review-strict
  name: Consensys AI Code Review (Strict)
  description: Multi-agent AI code review - fails on HIGH severity or above
  entry: consensys review --quick --fail-on HIGH
  language: python
  types: [python]
  pass_filenames: true
  require_serial: false
  verbose: true
  stages: [commit]

- id: consensys-review-all
  name: Consensys AI Code Review (All Languages)
  description: Multi-agent AI code review for any file type
  entry: consensys review --quick
  language: python
  types_or: [python, javascript, typescript, go, rust, java, c, c++, ruby, php]
  pass_filenames: true
  require_serial: false
  verbose: true
  stages: [commit]
