# Example GitHub Actions Workflow for Consensys Code Review
#
# This workflow runs Consensys AI code review on every pull request.
# Copy this file to .github/workflows/consensys.yml in your repository.
#
# Configuration:
#   1. Add ANTHROPIC_API_KEY to your repository secrets
#   2. Adjust fail_on threshold as needed (LOW, MEDIUM, HIGH, CRITICAL)
#   3. Enable/disable PR comments with post_comment

name: Consensys Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    # Only trigger on specific file types (optional)
    # paths:
    #   - '**.py'
    #   - '**.js'
    #   - '**.ts'

  # Allow manual trigger
  workflow_dispatch:
    inputs:
      fail_on:
        description: 'Minimum severity to fail the check'
        required: false
        default: 'HIGH'
        type: choice
        options:
          - LOW
          - MEDIUM
          - HIGH
          - CRITICAL

# Prevent concurrent runs on the same PR
concurrency:
  group: consensys-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write  # Required for posting PR comments

jobs:
  review:
    name: AI Code Review
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for diff analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Consensys
        run: |
          pip install consensys
          consensys --version

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.py
            **/*.js
            **/*.ts
            **/*.go
            **/*.rs
            **/*.java

      - name: Run Consensys review
        id: review
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "Reviewing changed files..."
          echo "Files: ${{ steps.changed-files.outputs.all_changed_files }}"

          # Create review output file
          REVIEW_FILE="review-results.md"
          echo "# Consensys Code Review" > $REVIEW_FILE
          echo "" >> $REVIEW_FILE
          echo "**PR:** #${{ github.event.pull_request.number }}" >> $REVIEW_FILE
          echo "**Commit:** ${{ github.sha }}" >> $REVIEW_FILE
          echo "" >> $REVIEW_FILE

          OVERALL_STATUS="pass"
          FAIL_ON="${{ github.event.inputs.fail_on || 'HIGH' }}"

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "Reviewing: $file"
            echo "## $file" >> $REVIEW_FILE
            echo "" >> $REVIEW_FILE

            # Run review and capture output
            if consensys review "$file" --quick --fail-on "$FAIL_ON" 2>&1 | tee -a $REVIEW_FILE; then
              echo "- Status: PASS" >> $REVIEW_FILE
            else
              echo "- Status: FAIL" >> $REVIEW_FILE
              OVERALL_STATUS="fail"
            fi
            echo "" >> $REVIEW_FILE
            echo "---" >> $REVIEW_FILE
            echo "" >> $REVIEW_FILE
          done

          # Set outputs
          echo "status=$OVERALL_STATUS" >> $GITHUB_OUTPUT
          echo "review_file=$REVIEW_FILE" >> $GITHUB_OUTPUT

          # Exit with error if any review failed
          if [ "$OVERALL_STATUS" == "fail" ]; then
            echo "::error::Code review found issues at $FAIL_ON severity or higher"
            exit 1
          fi

      - name: Post PR comment
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reviewFile = '${{ steps.review.outputs.review_file }}' || 'review-results.md';

            let body = '## Consensys AI Code Review\n\n';

            if (fs.existsSync(reviewFile)) {
              body += fs.readFileSync(reviewFile, 'utf8');
            } else {
              body += 'No code files changed in this PR.';
            }

            body += '\n\n---\n*Generated by [Consensys](https://github.com/noah-ing/consensys)*';

            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const existingComment = comments.find(c =>
              c.body.includes('Consensys AI Code Review') &&
              c.user.login === 'github-actions[bot]'
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - name: Upload review artifact
        if: always() && steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: consensys
          path: review-results.md
          retention-days: 30

      - name: Skip message
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No reviewable files changed. Skipping review."

  # Optional: Run full review on main branch
  full-review:
    name: Full Review on Main
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Consensys
        run: pip install consensys

      - name: Run full batch review
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          consensys review-batch src/ --quick --report full-review.md || true
          echo "Full review completed"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: full-review-report
          path: full-review.md
          retention-days: 90
